version: "3"
services:
  dev-configs:
    image: dev-configs
    tty: true

    build:
      context: .
      dockerfile: Dockerfile
      network: host
      ssh: ["default"]

    hostname: dev
    ipc: host
    # network_mode: host

    # # gpu usage and profiling
    # cap_add:
    #   - SYS_PTRACE
    #   - SYS_ADMIN
    # security_opt: ["seccomp:unconfined"]

    # # gpu reservation
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]

    environment:
      - SSH_AUTH_SOCK:${SSH_AUTH_SOCK}

    ports:
      - "5757:5757"

    volumes:
      - ./:/workspace/configs/:cached

