return {
  -- shared
  'nvim-lua/plenary.nvim',
  'kyazdani42/nvim-web-devicons',

  -- colorschemes
  'p00f/alabaster.nvim',
  'FrenzyExists/aquarium-vim',
  'ribru17/bamboo.nvim',
  'w3barsi/barstrata.nvim',
  'kyazdani42/blue-moon',
  'projekt0n/caret.nvim',
  'DeviusVim/deviuspro.nvim',
  'sainnhe/everforest',
  '0xstepit/flow.nvim',
  'ellisonleao/gruvbox.nvim',
  'luisiacc/gruvbox-baby',
  'sainnhe/gruvbox-material',
  'mikesmithgh/gruvsquirrel.nvim',
  'w0ng/vim-hybrid',
  'chiendo97/intellij.vim',
  'savq/melange-nvim',
  'ramojus/mellifluous.nvim',
  'kvrohit/mellow.nvim',
  'miikanissi/modus-themes.nvim',
  'tanvirtin/monokai.nvim',
  'bluz71/vim-moonfly-colors',
  'thepogsupreme/mountain.nvim',
  'bluz71/vim-nightfly-guicolors',
  'talha-akram/noctis.nvim',
  'nyoom-engineering/oxocarbon.nvim',
  'JoosepAlviste/palenightfall.nvim',
  'olivercederborg/poimandres.nvim',
  'samharju/serene.nvim',
  'NTBBloodBath/sweetie.nvim',
  'protesilaos/tempus-themes-vim',
  'Mofiqul/vscode.nvim',
  'arzg/vim-colors-xcode',

  -- lua configured colorschemes
  'catppuccin/nvim',
  'marko-cerovac/material.nvim',
  'EdenEast/nightfox.nvim',
  'rose-pine/neovim',
}
