require('autocommands')
require('plugins')
require('settings')
require('keymaps')
require('lsp')
require('statusline')

require('plug-config/nerdtree')
require('plug-config/tagbar')
require('plug-config/tabline')
require('plug-config/gitgutter')
require('plug-config/tabular')
require('plug-config/nerdcommenter')
require('plug-config/autopairs')
require('plug-config/fzf')
